### PR TITLE
feat: add proper support for global accelerator

### LINKED ISSUE #50: ALIAS records for Global Accelerator are not supported
The AWS docs are misleading: https://docs.aws.amazon.com/general/latest/gr/global_accelerator.html

They state `globalaccelerator.amazonaws.com` as service endpoint. However, the `ALIAS` records need to point to `awsglobalaccelerator.com` in hosted zone `Z2BJ6XQ5FK7U4H`.

### PR DESCRIPTION
**Pull request by nodomain**
Fixes #50 :)

### CODE REVIEW

**Comment by nodomain** [comment]
I think this should work.

**Comment by ross** [comment]
`./script/format` should take care of what failed above. `./.git_hooks_pre-commit` will run everything that CI does.

**Comment by nodomain** [comment]
Please try again :)

**Review by ross — APPROVED** [review]
LGTM. Thanks.

**Pull request merged**
