### PR TITLE
Test Python 3.10

### PR DESCRIPTION
**Pull request by hugovk**
Need quotes around "3.10" otherwise YAML thinks it's 3.1: https://dev.to/hugovk/the-python-3-1-problem-85g

### CODE REVIEW

**Comment by hugovk** [comment]
Aha, the Python 3.10 failure is because nose is long unmaintained and doesn't support 3.10:

https://github.com/nose-devs/nose/issues/1099 says 3.9, but they moved it to 3.10.

I suggest moving to nose2 or preferably pytest.

**Comment by ross** [comment]
> Aha, the Python 3.10 failure is because nose is long unmaintained and doesn't support 3.10:

Yeah. I have a set of changes being made to https://github.com/octodns/octodns-template atm to switch it over to pytest similar to https://github.com/octodns/octodns-azure/pull/3, though I've since learned that pytest has built in coverage requirements support so I'll be switching to that as well, e.g. https://github.com/octodns/octodns-constellix/pull/5/files#diff-b0ddc24027292e24c495fb6a8df798ce6f62bd9b2a89e23b97d56e041e29b5a1R43. Once the template bits have been updated I plan to go through and apply the changes to all the existing repos. 

Anyway. If you want once the template changes are up to reference you can mimic them here. Otherwise I'll pick it up once I'm there. 

Thanks.

**Comment by hugovk** [comment]
Sounds like a plan! Feel free to add this whenever you like, and you can close this PR in the meantime if you like 👍

**Comment by ross** [comment]
https://github.com/octodns/octodns-route53/pull/9 replaces this and pulls in other similar template updates/fixes. Thanks

**Pull request closed without merging**
