### PR TITLE
Version 0.0.4 bump and CHANGELOG update

### PR DESCRIPTION
**Pull request by ross**
## v0.0.4 - 2022-02-02 - pycountry-convert install_requires

* install_requires includes pycountry-convert as it's a runtime requirement
* other misc script/tooling improvements

### CODE REVIEW

**Comment by ross** [comment]
https://github.com/octodns/octodns/pull/869 removes pycountry and https://github.com/octodns/octodns/pull/866 removed pycountry-convert from octoDNS core.

**Comment by viranch** [comment]
The current latest version (0.0.3) of octodns_route53 will not be compatible with future version of octodns (due to the lack of pycountry). How do we indicate this in setup.py?

More long term, it looks like we're saying that octodns_route53 will stay compatible with future versions of octodns (`octodns>=0.9.14` in setup.py). That doesn't seem like a safe assumption? If there's a new incompatible release of core, the provider modules will allow installing a broken version combination.

May be we should update the core dependency to `octodns==0.9.14` (instead of `>=0.9.14`) in this PR? That way providers can catch up independently instead of having to update them before an incompatible release of core.

**Comment by ross** [comment]
> The current latest version (0.0.3) of octodns_route53 will not be compatible with future version of octodns (due to the lack of pycountry). How do we indicate this in setup.py?

I don't think i'd say incompatible really. It'll work fine, it just wouldn't atomically get pycountry-convert installed and that issue should be fairly immediately clear if someone runs into it. 

> More long term, it looks like we're saying that octodns_route53 will stay compatible with future versions of octodns (`octodns>=0.9.14` in setup.py). That doesn't seem like a safe assumption? If there's a new incompatible release of core, the provider modules will allow installing a broken version combination.

Not really sure how we'd address that ahead of time unless we did something like `>=0.9.14;<1.0.0` to preemptively carve out a way to make breaking changes someday.

More generally I'd plan to preserve backwards compatibility unless absolutely necessary to break it. There are a number of places in manager.py that already do this trying with old call signatures if the new ones fail etc. 

Definitely don't discount the potential issue here, but not sure we'd be able to effectively solve it ahead of time.

> May be we should update the core dependency to `octodns==0.9.14` (instead of `>=0.9.14`) in this PR? That way providers can catch up independently instead of having to update them before an incompatible release of core.

If it was more incompatible than requiring a manual install of `pycountry-convert` then I'd feel like that would be worth it. That coupled with very few people have probably having updated to the extracted providers setup given that octoDNS core hasn't released post extraction yet I kind of feel like we're OK and that most people will end up grabbing 0.0.4 when they make the switch.

**Comment by viranch** [comment]
Yep not too big a deal for now. Something to keep in mind for future if things were to get more incompatible.

**Review by viranch — APPROVED** [review]

**Pull request merged**
